# Generated by Django 4.0.5 on 2022-07-06 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=16)),
                ('qphone', models.CharField(max_length=16)),
                ('qemail', models.CharField(max_length=40)),
                ('qselect', models.CharField(max_length=20)),
                ('qsubject', models.TextField()),
                ('context', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'qestion',
            },
        ),
    ]
