# Generated by Django 3.2.13 on 2022-07-05 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('ZIPCODE', models.CharField(max_length=7)),
                ('SIDO', models.CharField(max_length=7)),
                ('GUGUN', models.CharField(max_length=30, null=True)),
                ('DONG', models.CharField(max_length=50)),
                ('RI', models.CharField(max_length=100, null=True)),
                ('BUNGI', models.CharField(max_length=40, null=True)),
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zipcode',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=18, unique=True)),
                ('passwd', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.TextField()),
                ('mailing', models.BooleanField(default=False)),
                ('addr', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime.now)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='join.zipcode')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
