# Generated by Django 3.2.13 on 2022-07-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('appno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('pdate', models.DateField()),
                ('ptime', models.TimeField()),
                ('agent', models.CharField(max_length=10)),
                ('msg', models.TextField(null=True)),
                ('fnames', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('addr', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='InspFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insptype', models.CharField(max_length=4)),
                ('carsize', models.CharField(max_length=2)),
                ('carname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyUser',
            fields=[
                ('carno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=10)),
                ('carname', models.CharField(max_length=10)),
                ('apptel', models.CharField(max_length=10)),
                ('alttel', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=10)),
                ('addr1', models.CharField(max_length=10)),
                ('addr2', models.CharField(max_length=10)),
                ('usrappno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='check.apply')),
            ],
        ),
    ]
