# Generated by Django 3.2.13 on 2022-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='ptime',
            field=models.CharField(max_length=5),
        ),
    ]
