# Generated by Django 3.2.13 on 2022-07-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['-appno']},
        ),
        migrations.AlterModelOptions(
            name='centerinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='apply',
            table='apply',
        ),
        migrations.AlterModelTable(
            name='applyuser',
            table='applyuser',
        ),
        migrations.AlterModelTable(
            name='centerinfo',
            table='centerinfo',
        ),
        migrations.AlterModelTable(
            name='inspfee',
            table='inspfee',
        ),
    ]
