# Generated by Django 3.2.13 on 2022-07-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_rename_agid_apply_agid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='agid_id',
            new_name='agid',
        ),
    ]
