# Generated by Django 3.2.13 on 2022-07-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_rename_agid_id_apply_agid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('atno', models.CharField(max_length=12)),
                ('atame', models.CharField(max_length=10)),
                ('attel', models.CharField(max_length=10)),
                ('atfdate', models.CharField(max_length=10)),
                ('atedate', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-atid'],
            },
        ),
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['-appid']},
        ),
    ]
