# Generated by Django 3.2.13 on 2022-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_rename_atame_alert_atname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carzipcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sido', models.CharField(max_length=20)),
                ('gugun', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
            ],
        ),
    ]
